---
title: "R Notebook"
output: html_notebook
---



```{r}
library(readr)
library(tidyr)
library(tidyverse)
library(deldir)
library(data.table)
```


```{r}
# relative files
files = list.files("./../../../../../data/Risom_breast/Segmetation_Outlines_and_Labels_Mendeley/", pattern = ".csv$")
path = "./../../../../../data/Risom_breast/Segmetation_Outlines_and_Labels_Mendeley/"

scdat = read_csv("./../../../../../data/Risom_breast/Single_Cell_Data.csv")

table(scdat$)
```
Make file with cell type abundances for creating baseline for glm
```{r}
abundances = scdat %>% select(Point_Num, sublineage)
abundances = as.data.frame.matrix(t(prop.table(t(table(abundances$Point_Num, abundances$sublineage)), margin = 2)))
write.csv(abundances,file="./../../results_Risom/baseline_cellcount_sublineage.csv",row.names = TRUE)

```



Check one file first

```{r}
#merge centroid information to sc dataset
### here I select sublineage, cellline has less cells and could also be generated
scdat = scdat %>% select("label", "Point_Num", "celllineage")
scdat$Point_Num = as.character(scdat$Point_Num)

for(i in 1:length(files)){
  dat = read_csv(paste0(path, files[i]))
  dat$Point_Num = rep(sub(".csv", "", files[i]), nrow(dat))
  dat = left_join(dat, scdat, by = c("label", "Point_Num"))
  dat = dat %>% select("centroid-0", "centroid-1", "celllineage")
  colnames(dat) = c("x", "y", "ct")
  
  write_csv(dat, paste0("./../../../../../data/Risom_breast/processed_files_celllineage/", files[i]))
}

```


