---
title: "scimap_spatial_interaction_results"
output: html_notebook
---

```{r}
library(readr)
library(pheatmap)
library(tidyverse)
```


```{r}
#read in results
#path = "./../../../../SCNA_masterthesis_results/asym01_1000_grid0.2_1kiter_025kswap_scimap_spatial_interaction.csv"
path = "./../../../../SCNA_masterthesis_results/asym01_1000_grid0.2_1kiter_025kswap_scimap_dirSEA_spatial_interaction.csv"
df = read_csv(path)
```


```{r, fig.width= 15, fig.height= 6}
df = as.data.frame(df)
rownames(df) = df$new_column
df = df[ ,-(ncol(df))]

subset_values = df[, !grepl("pvalue", names(df))]

pheatmap(subset_values, 
         cluster_rows = F, 
         cluster_cols = F, 
         na_col = 'grey')
```
```{r, fig.width= 20, fig.height= 6}
df = as.data.frame(df)
rownames(df) = df$new_column
df = df[ ,-(ncol(df))]

subset_values = df[, grepl("pvalue", names(df))]

pheatmap(subset_values, 
         cluster_rows = F, 
         cluster_cols = F, 
         na_col = 'grey')
```


```{r}
#save the file correctly: subset_values
subset_values = as.data.frame(t(subset_values))
colnames(subset_values) = gsub("X", "", colnames(subset_values))
colnames(subset_values) = gsub("__", "_", colnames(subset_values))
colnames(subset_values) = gsub("\\.0", "", colnames(subset_values))

subset_values <- subset_values[order(rownames(subset_values)), ]

#save as csv for comparison
write.csv(subset_values, "./../../results_4ct_asym_0.2grid_self/scimap_dirSEA_knn8_4ct_cross01.csv")

```


compare to dirsea heatmap

```{r}
dirSEA = read_csv('./../../../Comparison/results_4ct_asym_0.2grid_self/SEA_bi_direction_delaunay_4ct_cross01.csv')
dirSEA = as.data.frame(dirSEA)
rownames(dirSEA) = dirSEA$...1
dirSEA = dirSEA[ ,-1]

pheatmap(as.data.frame(dirSEA),
         na_col = 'grey')
```






