---
title: "check_value distrbution"
author: "Chiara Schiller"
date: "2023-07-04"
output: html_document
---

This script checks the distribution of the interactions scores of a tool.

```{r}
# Install packages
library(FactoMineR)
library(ggcorrplot)
library(corrr)
library(readr)
library(ggfortify)
library(ggplot2)
library(randomForestSRC)
library(caret)
library(tidyverse)
library(factoextra)
library(pheatmap)
```

Load in  different result files, the normal sample by interaction value matrix
```{r}
csv_dir = "./../../results_4ct_sym_0.2grid_self/distribution_check/"
data <- list.files(path = csv_dir, recursive = FALSE, pattern = "\\.csv$")
all = list()
for (i in 1:length(data)){
  all[[i]] <- as.data.frame(read_csv(paste0(csv_dir,data[i])))
  #rownames(all[[i]]) = sub("4ct_self", "", as.vector(all[[i]][,1]))
  rownames(all[[i]]) = as.vector(all[[i]][,1])
  rownames(all[[i]]) = sub(".csv", "", rownames(all[[i]]))
  all[[i]] = all[[i]][,-1]
}

```

Create preference and abundance group columns within datasets
```{r}
df_list = list()

for (i in 1:length(all)){
  #all[[i]]$preference <- sub("_ab.*sim_\\d+$", "", rownames(all[[i]]))
  #all[[i]]$preference <- sub("self_", "self0_", all[[i]]$preference)
  all[[i]]$preference <- sub("_ab.*$", "", rownames(all[[i]]))
  all[[i]]$preference <- sub("_ab.*$", "", all[[i]]$preference)
  all[[i]]$abundance <- sub(".*ab", "ab", rownames(all[[i]]))
  all[[i]]$abundance = sub("_[0-9]+$", "", all[[i]]$abundance)
  all[[i]]$abundance = sub("_sim", "", all[[i]]$abundance)
}
```


Naming convention for comparison of cohorts per tool: Tool_x_vs_y
```{r}
# prepare lists
df_comb = list()
split_string <- strsplit(data, "4ct")
#toollist <- sub("_+$", "", split_string[[1]][1])
#part_after_sim <- paste("sim", split_string[[1]][2], sep = "")

# now loop through every combination of abundances are preferences to compare all tools withtin their abundances
for (i in 1:length(all)){
  combs <- combn(unique(all[[i]]$preference), 2)
  pref_comb <- apply(combs, 2, function(x) c(as.character(x[1]), as.character(x[2])))
  for (a in unique(all[[i]]$abundance)){
  df = all[[i]] %>% filter(abundance == a)
    for (p in 1:ncol(pref_comb)){
      df2 = df %>% filter(preference %in% pref_comb[,p]) 
      df_comb[[paste(sub("_+$", "", split_string[[i]][1]), unique(df2$abundance), unique(df2$preference)[1], "vs", unique(df2$preference)[2], sep = "_")]] = df2 %>% select(-preference, -abundance)
      #df_comb[[paste(sub("_+$", "", split_string[[i]][1]), unique(df2$abundance), paste(pref_comb[,p], sep = "_vs_"), sep = "_")]] = df2
      }
    }
  }

# these are the comparisons we have:
names = names(df_comb)
names(df_comb)
all = df_comb
```

Look at distribution of markers for strong preference

```{r}
# select which dataset to look at based on index and naming of comparison above
df = all[[45]]
df = df[,1]
df = as.data.frame.matrix(cbind(df[1:100], df[101:200]))
colnames(df) = c("self_0.45", "self_0.6")
df = gather(df, key = "adjacency", value = "interaction_score")

# create histogram of interaction score
png("./../../../../Figures/raw/distribution_check/SEA_045vs06_ab025_interaction_score.png", height = 650, width = 1100, res = 200)
ggplot(df, aes(interaction_score, fill = adjacency)) +
  geom_histogram() +
  facet_grid(.~adjacency) +
  theme_test() +
  ggtitle("SEA_0.25_self_0.45_vs_self_0.6")
  
dev.off()
```


```{r}
sessionInfo()
```

